language: cpp

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libgmp-dev
  
compiler:
  - gcc
  - clang

script:
- mkdir build
- cd build 
- cmake ..
- make
- ./ys2 ../examples/bs_tree.ys

notifications:
  email: false
